### ISSUE TITLE
Add lzf compression support

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-client#104]
Compression can improve response times considerably. Lightblue server already supports it, now is the time to implement this functionality in the java client.

We're relying on this project: https://github.com/svanoort/rest-compress/

**Comment by dcrissman** [comment]
I believe this has been implemented at this point. Is there any reason not to close this issue out?

**Comment by dcrissman** [comment]
@paterczm could you confirm if this ticket can be closed?
