### ISSUE TITLE
Many metadata requests make requests for completely different APIs depending on which constructor you use or if you use `setEntityName` or `setEntityVersion`

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-client#106]
For example:

`new MetadataGetEntityNamesRequest("user", "1.0.0").getRestURI("http://lightblue.com/metadata/rest");`

will return: `http://lightblue.com/metadata/rest/user/1.0.0`

Which is get metadata request

Likewise, if you pass only entity, it is a get versions request.

**Comment by dcrissman** [comment]
Changes were made in #176 for this issue. Closing, but feel free to reopen if you feel something was missed.
