### ISSUE TITLE
Make trust of self-signed certs configurable

### ISSUE THREAD

**Issue by derek63** [lightblue-platform/lightblue-client#11]
Right now the client has it hard-coded to accept all certificates (SSLConnectionSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER).  This should be configurable to allow any of the available values (ALLOW_ALL_HOSTNAME_VERIFIER, BROWSER_COMPATIBLE_HOSTNAME_VERIFIER, STRICT_HOSTNAME_VERIFIER)

**Comment by jewzaam** [comment]
@derek63 what is the impact of not doing this?  Do we care for our managed envs?

**Comment by alechenninger** [comment]
Fixed in #321
