### ISSUE TITLE
enums as a separate package is inconvenient

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-client#111]
Packages are a logical organization of source code based on responsibilities. Putting all enum classes in a separate package is inconvenient, wrong, and ugly. Following the same paradigm, all applications can have three packages: enums, interfaces, concrete classes.

Put the enum in the package it is used.

**Comment by alechenninger** [comment]
+1

I try to think of packages in terms of the domain model (e.g. "package by feature" vs "package by type")

**Comment by bserdar** [comment]
Enums are deprecated.
