### ISSUE TITLE
Date should be handled by the client code, not the caller

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-client#112]
Instead of:
   withValue("scheduledDate",ExpressionOperation.LTE,ClientConstants.getDateFormat().format(new Date())

I should be able to write:
withValue("scheduledDate",ExpressionOperation.LTE,new Date())

The implementation should check if the value is date, and format it.

**Comment by dcrissman** [comment]
+1

**Comment by dcrissman** [comment]
This is now handled by the Literal class. Closing.
