### ISSUE TITLE
Filtering out migration metadata

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-client#113]
All migrated documents contain data as following:
```json
"createdBy":"lightblue-consistency-checker",
"lastUpdatedBy":"lightblue-consistency-checker",
"migrationDate":"20150504T18:08:42.160+0000",
"migratedFrom":"jdbc:oracle:thin:@webdev-scan.corp.redhat.com:20010:WEBDEV1"
```
The applications don't care about those fields and it would be nice to filter them out at the lightblue client level, without a need to specify the filtering projection for each call.

I'm thinking about a new lightblue-client feature:
```java
lightblueClient.setProjection(excludeField("migrationDate"), excludeField("migratedFrom"))
```
A client configured like this would append specified projections to every call. This will produce cleaner json and can slightly improve response times.

**Comment by dcrissman** [comment]
This exists now in the form of
Projection.excludeField

Closing.
