### ISSUE TITLE
Support Bulk Request

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-client#154]
Feature recently added to lightblue-core and lightblue-rest.

**Comment by BVulaj** [comment]
Changes being worked on in [BVulaj/lightblue-client](/BVulaj/lightblue-client/tree/154-bulk-support).

**Comment by BVulaj** [comment]
Starting work on tests.  If anyone would like to preemptively check this out, it's probably in a good state to do so.
