### ISSUE TITLE
Cut down on verbosity of updating entities

### ISSUE THREAD

**Issue by BVulaj** [lightblue-platform/lightblue-client#165]
The current client interface requires the user to specify fields to update on the request rather than just taking the entity and updating the necessary fields.  We should provide this as an option as well.

**Comment by bserdar** [comment]
Does Literal.pojo() solve this?

**Comment by BVulaj** [comment]
Maybe, how would you use that in the current API?  Any examples or tests?

ie:

```java
request.updates(Update.set("x"), Literal.pojo(x));
```

I don't think that solves this use case.  The consumer of the client still has to explicitly specify every field at the top level that he intends to update.  Since the LB client is very ORM like, I tend to look to Hibernate as an example of how one may use this client. (Maybe a mistake on my part)

As a user, I want to be able to update an entity by just updating it's POJO's fields and persisting it without specifying the individual fields that I would like updated, unless otherwise stated.  This makes writing services (like we're doing now) much more verbose than they really need to be.

What I'd like to see people be able to do:

```java
DataUpdateRequest req = new DataUpdateRequest("entity", "1.0.0");
req.where(Query.withValue("id", Query.eq, id);  
// maybe not even require this `where`.  Use JPA annotations or something LB specific and scan for an annotated ID field.  Just a high level thought.
// no req.updates required.  Update all fields by default.  Or, only all changed fields.
lbClient.data(req, Entity.class);
```

Convention over configuration.  I think that's probably the root of what I'm trying to get at.  This is maybe going further down the road, but it would also allow users to write generic services without having to re-write all of the boiler plate for the basic operations.

See [here](/BVulaj/persistence-api-hibernate/blob/master/src/main/java/com/bvulaj/persistence/HibernateRepository.java) for a Hibernate example of something that accomplishes this at a *very simple* level.
A [more complete](https://code.google.com/p/hibernate-generic-dao/wiki/UserGuide) example from Google.

**Comment by bserdar** [comment]
What you are describing is the save operation. Update operation updates
selected fields. Save operation rewrites the entity.

**Comment by bserdar** [comment]
Can we close this?

**Comment by BVulaj** [comment]
Closing.

This is solved by using the Save API instead of the Update API.
