### ISSUE TITLE
DefaultLightblueResponse has error API's but a LightblueResponseException is thrown when there is an error

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-client#169]
The API's that return `LightblueResponse` are confusing because of this.

I would either:
1. Remove error API's from LightblueResponse (it becomes a "success lightblue response") and then only return/create it when you have a successful response. The LightblueException contains the error information you need (you will never interact with a response object for successful response if you don't have a successful response).
2. Or do not throw a LightblueException if you are asking for a LightblueResponse. I'm asking the API for an encapsulation of Lightblue's response, which may contain errors, or other information. But you are throwing an exception when that response contains an error, _getting in the way of me just examining Lightblue's response, which is what I asked for, and the API is telling me that it will give me_.

I prefer option 2 but either are better than current state.

The argument to throw an exception when there are errors in the response is to save code and to "error when there is an error." But...
- There is already error information in the response object. There are more ways to show "an error has occurred" than exceptions. Some languages don't even have exceptions at all. So having both is surprising. I would've expected that information to just fall into the response because the API is telling me that's where it will be.
- If you want to save code, you also generally want to parse to a model object, and you will be using an API that does not return a `LightblueResponse`. This scenario is therefore unaffected, and unsurprising, and everyone's happy. Admittedly, this is mainly for find operations, other operations you probably don't care about the response, but still want an exception on error.

**Comment by alechenninger** [comment]
Another option would having two API's, say there's another one like `mandatoryData(....)`, which threw an exception on any error. Or something like this.

You see this in some API's commonly. For instance, Camel has API's for getting message body's which throws an exception if the body is null (`getMandatoryBody()`). But `getBody()` does not.

**Comment by dcrissman** [comment]
Another thing to think about now is BulkLightblueResponse. In it's constructor DefaultLightblueResponse instances are created, so if one of them had an error/data error the entire batch would fail out while parsing the response without finishing other potentially valid responses. We could add a try/catch, but that defeats the purpose of the exception and creates a mess of it's own.

With compounding problem this causes, I am siding with option 2 also.

Couple of thoughts:
* We might then be able to get rid of LightblueResponseException altogether or move it to the Http layer.
* BulkLightblueResponse also throws a LightblueResponseException for an invalid seq id, which we would need to replace. I guess my question there is should a bad seq number, cause the entire batch to fail?

**Comment by jewzaam** [comment]
LightblueResponse no longer has error api's.  If there's a response error you'll have a LightblueResponseException thrown that contains an instance of LightblueErrorResponse.  Should this issue be closed?

**Comment by dcrissman** [comment]
@jewzaam I updated the subject to reflect recent changes. The core concern raised still stands.

**Comment by jewzaam** [comment]
DefaultLightblueResponse is the implementation class.  The client just exposes the interfaces.  You're asking for an impl of each interface in separate classes?  Don't think that would be a problem.

**Comment by alechenninger** [comment]
I agree since option 1 was implemented I think this can be closed, at least my original concern is addressed, feel free to reopen or open a new issue.

**Comment by dcrissman** [comment]
Clearly I misunderstood something about this ticket and I didn't realize it had been completed anyway. I do however see another issue, but will open a different issue for it.

**Comment by dcrissman** [comment]
Clearly I misunderstood something about this ticket and I didn't realize it had been completed anyway. I do however see another issue, but will open a different issue for it.

**Comment by dcrissman** [comment]
#202 is the new issue.
