### ISSUE TITLE
Need convenience methods to deal with case insensitive search

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-client#179]
This needs to be implemented in core, but until then, client can provide something like this:

Query.withValue_ci("field","value")

This would write a regex query that searches for "value" case insensitive, so it:
  1) Escapes special chars in "value"
  2) Writes a regex query with case insensitive flag set

Also, make that escape function static public. Escape all possible regex special chars.

**Comment by BVulaj** [comment]
Writing regex for the BinOps / NaryOps could be a little weird.  How should we handle things like gt and lt?  Using regex we can only match, partial match, or no match.

**Comment by bserdar** [comment]
Query.withValue_ci("field","value")


i.e. no op. Always eq.

**Comment by BVulaj** [comment]
That makes sense.  Do you think having neq is useful for this operation though?

To keep the interface in line with the current conventions, I think I'd rather have it look something like:

    withValue(String field, BinOp op, Literal value, boolean caseInsensitive);

or to only support eq:

    withValue(String field, Literal value, boolean caseInsensitive);

In the first example we can throw UnsupportedOp if != eq || neq

**Comment by bserdar** [comment]
I don't like runtime syntax checks. If it is invalid, it shouldn't compile.
