### ISSUE TITLE
Exception inconsistency

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-client#188]
```java
user = lbClient.data(dfr, LBUser.class)
```
will throw LightblueException. However,
```java
LightblueResponse r =  lbClient.data(dfr);
user r.parseProcessed(User.class)
```
will throw both LightblueException and LightblueResponseParseException. I find this behavior inconsistent, because we execute exactly the same steps in both cases (call lightblue, parse json response to create a pojo).

http/src/main/java/com/redhat/lightblue/client/http/LightblueHttpClient.java:
```java
    @Override
    public LightblueResponse data(LightblueRequest lightblueRequest) throws LightblueException {
        LOGGER.debug("Calling data service with lightblueRequest: {}", lightblueRequest.toString());
        return callService(lightblueRequest, configuration.getDataServiceURI());
    }

    @Override
    public <T> T data(AbstractLightblueDataRequest lightblueRequest, Class<T> type) throws LightblueException {
        LightblueResponse response = data(lightblueRequest);
        try {
            return response.parseProcessed(type);
        } catch (RuntimeException | LightblueResponseParseException e) {
            throw new LightblueHttpClientException("Error sending lightblue request: " + lightblueRequest, e);
        }
    }
```
This brings another question: how are LightblueException and LightblueHttpClientException different?

I'm not sure what the best way to clean this up is. Perhaps replace LightblueHttpClientException with LightblueException and make LightblueResponseParseException extend LightblueException?

**Comment by alechenninger** [comment]
IMHO the `data` API should not mangle the `parseProcessed` exceptions, and just remove the try/catch block from `data` entirely. It's weird and surprising that there is this alternate path from `parseProcessed` as you've pointed out. This API should just be sugar, not new behavior. Also, I'd stop throwing `LightblueHttpClientException` except for literally an exceptional situation with the client code itself (not sure where this would actually occur other than maybe an IOException trying to make the request).

Semantically it is important to discern from lightblue had a problem with your request versus the data couldn't be parsed to the model object you passed in, so those two different types (LightblueException and LightblueResponseParseException) of exceptions makes sense at a glance.

**Comment by paterczm** [comment]
@alechenninger, I agree with what you said. Looking at this closer, I think that exception handling in lightblue-client is inconsistent and confusing in general. This is not the first issue submitted, https://github.com/lightblue-platform/lightblue-client/issues/169 and https://github.com/lightblue-platform/lightblue-client/issues/143 also point at problems with exceptions.

I decided to redesign this altogether. Here are the exceptions I plan to include:
* LightblueException, a common parent to all lightblue exceptions
* LightblueHttpClientException, for http exceptions (no response or status != 200)
* LightblueResponseException, for when the response is valid, but contains errors. That means you can get a LightblueResponse object with errors only from this exception.
* LightblueResponseParseException, for json2pojo conversion errors

**Comment by dcrissman** [comment]
@paterczm I like what you suggest here, and indeed it looks like these changes were already made.

What about a distinction between a Data Error and a (Lightblue) Error? Maybe different exceptions for each type? Just thinking out loud. Thoughts?

**Comment by dcrissman** [comment]
I take back my earlier thought, I think LightblueResponseException is just fine. Closing.
