### ISSUE TITLE
Since bump to 2.0.0, there are other breaking changes we can make to remove deprecated stuff

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-client#190]
Few deprecated constructors, classes, etc. I know at least some of those can be removed pretty easily.

**Comment by jewzaam** [comment]
Just have to say.. in updating the unit tests it's amazing how cleaner the new stuff is.  Very nice to see the difference and the improvement.  Going to take a bit of time to clean it up though... ugg.

**Comment by jewzaam** [comment]
Read for review: https://github.com/lightblue-platform/lightblue-client/pull/197
