### ISSUE TITLE
Bulk Data Response with errored Data Responses does not process remaining responses

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-client#202]
DefaultLightblueBulkDataResponse iterates over the raw json, but passes the individual response to DefaultLightblueResponse to parse. If a DefaultLightblueResponse throws an exception while parsing, then the entire DefaultLightblueBulkDataResponse stops processing additional DefaultLightblueResponses. It is possible that there were successful DefaultLightblueResponse inter-mixed with the failed ones.

I feel that the BulkLightblueResponse should be constructed and returned with all responses on it, both failed and successful, regardless of exceptions. Let the client application figure out what to do with the failures.

**Comment by alechenninger** [comment]
What's the status on this? This is important to the event handler work we're doing since we're using bulk requests heavily.

**Comment by dcrissman** [comment]
This is not actively being worked on at this time as there are other higher priorities for us.

**Comment by alechenninger** [comment]
Alright, if I understand correctly, the parsing errors that would happen here would only be if the client had an incorrect understanding of the response coming from lightblue, which would be a lightblue or client bug and not a bug of a consumer of the client library?

**Comment by dcrissman** [comment]
Not sure what you mean exactly, but take the following bulk response for example:
response a. good
response b. error
response c. good
response d. error

In the above example, all you would get is a LightblueErrorResponse for b, with no mention of a, c, or d.

https://github.com/lightblue-platform/lightblue-client/blob/master/core/src/main/java/com/redhat/lightblue/client/response/DefaultLightblueBulkDataResponse.java#L40

**Comment by alechenninger** [comment]
Oh I see. `DefaultLightblueDataResponse` throws an exception if the response contains any kind of error. That's pretty bad for us. Can you prioritize fixing this?

**Comment by dcrissman** [comment]
@alechenninger I haven't formally created a PR yet because I want to write some unit tests first. That said, I would appreciate any feedback you may have. See my earlier commit.

**Comment by dcrissman** [comment]
@bserdar @jewzaam @BVulaj @paterczm @snehagunta - I would appreciate any of your input also.

Essentially what I am purposing is a breaking change to DefaultLightblueBulkDataResponse, that will allow all of the individual DefaultLightblueDataResponse to be parsed even if one/multiple have an 'error' or 'dataerror' on it, instead of failing the entire response and the client getting nothing.

This is consistent with the current DefaultLightblueDataResponse implementation of throwing exceptions when a 'error' or 'dataerror' is returned from lightblue.

* It will now collect any/all LightblueResponseException from the individual DefaultLightblueDataResponse instances created and re-package them into the new BulkResponseException.
* Seq exceptions (which should be rare/never I would think), instead of being thrown individually, will now just be included in the BulkResponseException.

**Comment by BVulaj** [comment]
I'm all for the user being able to collect successful responses, even if
there is a bad apple in the bunch.  You're proposing that we throw a
BulkResponseException, which will wrap all of the other errors, even if
there is one error.  Will the user have to collect the successful responses
from that Exception?

-Brandon

**Comment by dcrissman** [comment]
@BVulaj 

> You're proposing that we throw a BulkResponseException, which will wrap all of the other errors, even if there is one error

Correct.

> Will the user have to collect the successful responses from that Exception?

The client still get at the all responses (successful and errored, not seq exceptions) via the following call. This keeps sequenced order even for errored responses.
BulkResponseException#getBulkResponse().getResponses() or .getResponse(Request)

Just exceptions can be found at (including seq exceptions), these are effectively un-sequenced because of the seq exceptions:
BulkResponseException#getLightblueResponseExceptions

I didn't want to give too much effort to seq exceptions as I believe them to be rare, but I suppose we could pull them out into their own list so the client didn't have to sift through the other exceptions to find them?

**Comment by BVulaj** [comment]
@dcrissman I think it's slightly unintuitive, but I like what the pattern is trying to accomplish.  I'm not sure I have a better solution.

**Comment by dcrissman** [comment]
@BVulaj - Do you have any specifics of what you find unintuitive?

What if seq were stored and accessed separately from 'errors' and 'dataerrors'? That would make it easier to test for what kind of exceptions the client is dealing with. I was trying to keep the implementation simple, but I do think this would be confusing for the client.

**Comment by alechenninger** [comment]
First, thank you for looking at this.

I think your suggestion while not ideal is mostly consistent with the rest of the libraries behavior.

I would require a way to differentiate between "one or more individual responses failed" and "the bulk request itself failed fundamentally." If one or more individual responses failed, I will track those requests as failed and move on with the successes. If the bulk request failed completely, I will probably treat that scenario differently, either failing all of the requests (which have no responses at all in this scenario), or retrying, or something else.

Frankly my ideal has always been that a response object is returned without throwing an exception always unless lightblue failed to give any kind of usable response at all. This would include bulk responses and then this problem is solved. It is however of course convenient for the exceptions to be thrown when that's the behavior you want, so I would rather see an `Response assertSuccessful() throws LightblueException` (returns `this` or throws) or some such API on the response, or an intermediate object that has `Response get()` and `Response getUnlessFailed() throws LightblueException` returned from the various request methods. This adds one extra method call to callers who want this behavior, and no hassle or surprise for callers who don't want this behavior.

**Comment by dcrissman** [comment]
@alechenninger 

> I would require a way to differentiate between "one or more individual responses failed" and "the bulk request itself failed fundamentally."

Agreed, if the bulk response itself fails, then the appropriate exception should be directly thrown and not wrapped in a BulkResponseException. As it is now, if a bulk response is unable to parse the individual responses out of the json structure, then it will throw a LightblueParseException.

> If one or more individual responses failed, I will track those requests as failed and move on with the successes.

There are two tensions I am trying to keep. One, keeping responses in sequential order. Two, making it easy for the client to easily identify which responses have errors on them. 

To address the first tension, all responses, regardless of any errors (not including seq exceptions) are kept in the same ordered container.

For the second, BulkResponseException separately keeps the responses with errors (and seq exceptions).

**Comment by dcrissman** [comment]
Seq exceptions throw a monkey wrench in this as there is no way to know what position it was suppose to have. That throws the entire sequence of responses off as now the next sequential response takes the position of the missing response in getResponses(). This might require iterating over the sequence and building the List manually and fill in any sequence gaps with null values. Kind of icky.

**Comment by alechenninger** [comment]
> Agreed, if the bulk response itself fails, then the appropriate exception should be directly thrown and not wrapped in a BulkResponseException. As it is now, if a bulk response is unable to parse the individual responses out of the json structure, then it will throw a LightblueParseException.

That sounds good to me.

> To address the first tension, all responses, regardless of any errors (not including seq exceptions) are kept in the same ordered container.

> For the second, BulkResponseException separately keeps the responses with errors (and seq exceptions).

This also sounds good.

As far as seq exceptions goes, when do those occur? Personally I only care about errors/data errors with particular responses.

**Comment by dcrissman** [comment]
> As far as seq exceptions goes, when do those occur? Personally I only care about errors/data errors with particular responses.

When a non-numeric value is returned for the sequence or position of a response. As far as I can tell, this shouldn't even be possible. So I feel like I am going to a lot of work to try and not go to a lot of work on something that is a true exception case. Here is what I will do, instead of batching a sequence exception, I will just throw it if it happens. The consequence then to the client is that none of the responses would be parsed or returned, but as this is theoretically impossible, I would say there is a low risk of that happening.

I will probably throw a LightblueParseException instead of a LightblueResponseException though, as this is a problem parsing and not with the response itself.

**Comment by alechenninger** [comment]
That works for me. To me, I'll put that in the category of "bulk request failed fundamentally" and will just sort of, "throw my hands up" and let the exception propagate :).
