### ISSUE TITLE
Should throw meaningful exceptions when lb returns errors

### ISSUE THREAD

**Issue by jblashka** [lightblue-platform/lightblue-client#22]

**Comment by jewzaam** [comment]
Is this an issue still?  There are some issues around exception throwing that were resolved with the Ana release.

**Comment by jewzaam** [comment]
@jblashka still an issue?

**Comment by jewzaam** [comment]
@jblashka need info, will close soon otherwise.

**Comment by alechenninger** [comment]
As far as I can tell this is still an issue.

**Comment by alechenninger** [comment]
It looks like this was more or less implemented with #66 but I think the spirit of @jblashka 's request was more having more specific exceptions when something goes wrong based on the error code that Lightblue responds with.

**Comment by dcrissman** [comment]
I don't think we are going to create specific exceptions for each error code type. But PR #189 clarified the exceptions that do exist.

Is there anything further you would like? Or can we close this ticket out?
