### ISSUE TITLE
Usability issues with LightblueExternalResource and friends

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-client#223]
Trying to do some integration testing, these are the issues I'm having:

- What I am supposed to put for datasource information in entity metadata?
- Why do I have to provide JsonNodes for metadata when I can just get you the EntityMetadata object itself?
- I am getting NullPointerExceptions around loading datasource json files which don't exist. Nothing told me these should exist. What is supposed to be there? Why do I need them? Why not something more descriptive than an NPE? No javadoc to answer any of these questions.

**Comment by dcrissman** [comment]
Better documentation around testing is absolutely needed.

> What I am supposed to put for datasource information in entity metadata?

For test metadata you can (but don't have to) use the substitution string ${mongo.datasource}. For non-test metadata use whatever datasource name you want.

It was found that sometimes there would be mismatches in datasource names between internal, external, and test metadata. Substitution was the first solution to unify them for testing.

Later getDatasource was added to AbstractCRUDTestController and can be overridden to change all the values, but not currently available via LightblueExternalResource.

> Why do I have to provide JsonNodes for metadata when I can just get you the EntityMetadata object itself?

I did not look into using EntityMetadata, but the LightblueFactory requires a JsonNode for metadata files.

> I am getting NullPointerExceptions around loading datasource json files which don't exist.

Yup, a bug. A better exception should be provided.

> Nothing told me these should exist. What is supposed to be there?

Agreed, needs documentation. See https://github.com/lightblue-platform/lightblue-camel/tree/master/src/test/resources for the files you need.

The plan originally was to provide default versions upstream that would just exist runtime, but later there was a discussion that decided every projection should provide its own.

**Comment by alechenninger** [comment]
Thanks Dennis! This helps. I managed to pull some of the files from lightblue-client project, so I'm up and running. Would be great to streamline this experience for newcomers.

**Comment by alechenninger** [comment]
Here's what I'm doing to generate JSON instead of making it by hand:

```java
public abstract class TestMetadataJson {
    private static final Extensions<JsonNode> extensions = new Extensions<JsonNode>() {{
        addDefaultExtensions();
        registerDataStoreParser("mongo", new MongoDataStoreParser<>());
    }};

    private static final JsonNodeFactory jsonNodeFactory = JsonNodeFactory.withExactBigDecimals(true);
    private static final JSONMetadataParser parser = new JSONMetadataParser(extensions, new DefaultTypes(), jsonNodeFactory);
    private static final MetadataGenerator metadataGenerator = new MetadataGenerator(new JavaBeansReflector());

    public static LightblueExternalResource.LightblueTestMethods forEntity(Class<?> entityClass) {
        EntityMetadata entityMd = metadataGenerator.generateMetadata(entityClass);
        entityMd.setDataStore(new MongoDataStore("${mongo.database}", "${mongo.datasource}", entityMd.getName()));

        return new LightblueExternalResource.LightblueTestMethods() {
            @Override
            public JsonNode[] getMetadataJsonNodes() throws Exception {
                return new JsonNode[] {parser.convert(entityMd)};
            }
        };
    }
}
```

I use this like so:

```java
    @ClassRule
    public static LightblueExternalResource lightblueExternalResource =
            new LightblueExternalResource(TestMetadataJson.forEntity(NotificationEntity.class));
```

Cheers

**Comment by dcrissman** [comment]
@alechenninger That could be an interesting utility class to share, but probably belongs in core com.redhat.lightblue.test package.

**Comment by dcrissman** [comment]
> I am getting NullPointerExceptions around loading datasource json files which don't exist. Nothing told me these should exist. What is supposed to be there? Why do I need them? Why not something more descriptive than an NPE? No javadoc to answer any of these questions.

Split into a separate ticket: #239

**Comment by dcrissman** [comment]
>> Nothing told me these should exist. What is supposed to be there?

>Agreed, needs documentation. See https://github.com/lightblue-platform/lightblue-camel/tree/master/src/test/resources for the files you need.

>The plan originally was to provide default versions upstream that would just exist runtime, but later there was a discussion that decided every projection should provide its own.

Moving this too: https://github.com/lightblue-platform/lightblue-client/issues/191

**Comment by dcrissman** [comment]
@alechenninger I believe that addresses your concerns in this issue. I will close it out now, but please let me know if something was missed.
