### ISSUE TITLE
Support try-with-resources syntax for locking

### ISSUE THREAD

**Issue by kahowell** [lightblue-platform/lightblue-client#229]
`com.redhat.lightblue.client.Locking` or similar could produce `java.io.Closeable` instances.

Then locks could be used in try-with-resources statements, which would be convenient.

**Comment by alechenninger** [comment]
I actually experimented a bit with this originally but decided it was not necessary at the moment.

A locking abstraction will come in handy when we correctly deal with TTLs and "reacquiring" when it is still available. That may be a good time to use this construct.

**Comment by dcrissman** [comment]
I assume the desire then would be for #release() to be called from the #close() method? The issue is that the resourceId is unknown at this point as the client could be using a single Locking instance to manage multiple locks.

**Comment by bserdar** [comment]
It can be done with a new api in Locking:

  Lock lock(String resourceId,long ttl);

where Lock is:

public class Lock implements Closeable {
    private final String resourceId;
    private final Locking locking;

    void close() { locking.release(resourceId);}
    ... other Locking methods
}

**Comment by dcrissman** [comment]
I thought of that too, but had initially dismissed it because I wasn't sure I liked the syntax flow. Thinking about it again this morning, that is the right way to go. I cut a PR with the changes and will move any discussions over there. See #241.
