### ISSUE TITLE
Integration Testing: NPE when missing required files. 

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-client#239]
I am getting NullPointerExceptions around loading datasource json files which don't exist. Nothing told me these should exist. What is supposed to be there? Why do I need them? Why not something more descriptive than an NPE? No javadoc to answer any of these questions.

**Comment by dcrissman** [comment]
@alechenninger - This issue was resolved upstream. Closing.

**Comment by alechenninger** [comment]
Thank you!
