### ISSUE TITLE
Add toString impls to Error types

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-client#261]
It is painful to describe these as strings for debugging / error handling without this

**Comment by dcrissman** [comment]
I assume you meant the Response Exceptions, but I am not sure what you are asking to be included in the toString response.

**Comment by alechenninger** [comment]
I mean Error and DataError. I want the context, msg, and error code. Right
now I have to build strings of that myself. Unless I'm missing something?
