### ISSUE TITLE
Rename LightblueTestMethods ?

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-client#270]
This type name never made sense to me. It has one method "getMetadataJsonNodes" so to me this is a "MetadataJsonFactory". Yay/nay?

**Comment by dcrissman** [comment]
My thinking was that we might eventually need/want to add other methods to support the underlying LightblueClientTestHarness implementation. That said, I am not married to the name.

The only other methods that might make sense to be included in that Interface are: getLightblueCrudJson() and getLightblueMetadataJson(). Both of which your name would work for.

**Comment by alechenninger** [comment]
That's fair. Maybe LightblueTestHarnessConfiguration (or shorten to Config) if you want to keep it very generic. LightblueTestMethods to me implies it has methods which are tests.

**Comment by dcrissman** [comment]
I can buy that argument. Agreed.
