### ISSUE TITLE
Convert REST tests to Arquillian

### ISSUE THREAD

**Issue by derek63** [lightblue-platform/lightblue-client#37]
Pulled in from https://github.com/lightblue-platform/secant/issues/13

**Comment by luan-cestari** [comment]
I will take a look

**Comment by jewzaam** [comment]
A few things to make this not desirable:
- we don't get benefit of CDI with lightblue
- we have problems with embedded wildfly
- there are other test tools being developed that make this unnecessary
- we have Docker for integrated testing environment
