### ISSUE TITLE
Inject an HttpClient instead of new-ing it up internally inside LightblueHttpClient

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-client#42]
From https://hc.apache.org/httpcomponents-client-ga/tutorial/html/connmgmt.html

> 2.1. Connection persistence
The process of establishing a connection from one host to another is quite complex and involves multiple packet exchanges between two endpoints, which can be quite time consuming. The overhead of connection handshaking can be significant, especially for small HTTP messages. One can achieve a much higher data throughput if open connections can be re-used to execute multiple requests.

Sure, it makes it easy for clients to use because they don't have to worry about handling an HttpClient in their code, but this seems lazy to me. There should be a better way for clients to manage the life cycle of an HttpClient in various service and web frameworks that they use, rather than have the service client make a new connection for every service call. Currently the lightblue client gives no such option; it must manage the HttpClient, and gives no interface for a consumer to close it at some point, so it must close it after every request.

**Comment by alechenninger** [comment]
Fixing this is fairly straightforward though not trivial, and in doing so would close #50 as well.

Currently, `LightblueClient` news up its own `HttpClient` dependency by way of `HttpClientNoAuth` and `HttpClientAuth` classes, which are really just factories for Apache `HttpClient`s. This has a number of problems, which is in part why those classes are deprecated. The most egregious of these is #42 , in addition to this class being non-unit-testable, because it will always try to make real HTTP requests.

The solution is the dependency injection (aka inversion of control) pattern. This means that `LightblueClient` should accept an `HttpClient` in it's constructor, instead of "controlling" the implementation of that dependency itself.

However, one step further would be to avoid coupling to Apache's `HttpClient` interface at all, and instead provide our own simple interface. Another option would be to use [Google's http client library][1], which is exactly that: an abstraction around various possible HTTP client implementations, which may be Apache, vanilla java.net, or anything else. Of course, there is some concern around coupling to Google's API's themselves, so it seems as though the best compromise is to roll our own (though there can still be an implementation that uses Google's APIs, which would probably be a good idea to leverage that OSS work that is already done.. I'm reminded of effective java 47: Know and use the libraries).

Work that would need to be done:
- [ ] Design API for http clients. Will need to be at least three interfaces: Request, Response, and the Client itself. (Names TBD)
- [ ] Provide one or more stock implementations. One of which must not require explicit shutdown to maintain compatibility with the existing client. That is, so the `new LightblueClient()` can still work... it will just choose a default implementation that does not require explicit shutdown (like java.net).

[1]: https://github.com/google/google-http-java-client

**Comment by dcrissman** [comment]
If I might step back for a minute, what are the reasons that HttpClientAuth and family were deprecated? Could we not keep them as default or simple implementations if someone chose to use or extend them?

I am not necessarily opposed to being tied to Apache's HttpClient, although I could see the purposed decoupling idea as a follow up at some point down the road.

**Comment by alechenninger** [comment]
I deprecated them because I thought they duplicated a lot of things from the (IMHO) more readable / flexible factory classes that exist in their stead.

For instance, in `LightblueHttpClient`, there is currently:

```java
    private CloseableHttpClient getLightblueHttpClient() {
        CloseableHttpClient httpClient;
        if (configuration.useCertAuth()) {
            LOGGER.debug("Using certificate authentication");
            httpClient = new HttpClientCertAuth(configuration).getClient();
        } else {
            LOGGER.debug("Using no authentication");
            httpClient = new HttpClientNoAuth().getClient();
        }
        return httpClient;
    }
```

This could be replaced with just:
```java
    private CloseableHttpClient getLightblueHttpClient() {
        try {
            return ApacheHttpClients.fromLightblueClientConfiguration(configuration);
        } catch (GeneralSecurityException | IOException e) {
            LOGGER.error("Error creating HTTP client: ", e);
            throw new RuntimeException(e);
        }
    }
```

The main problem with either approach is that they are creating specific instances of a real http client within the class itself. This is a dependency which should be injected instead.

**Comment by dcrissman** [comment]
How about two implementations of LightblueClient? One that takes an existing HttpClient and allows the client code to manage the lifecycle, and another that just takes a LightblueClientConfiguration that open/closes the connection each time?

**Comment by alechenninger** [comment]
I could see that I guess but, then the existing implementation is still not testable, and it's not really a good design IMHO.

**Comment by dcrissman** [comment]
I hear your point about testing.

I guess my main thought is that I would like to keep the client as simple to use as possible.

**Comment by kahowell** [comment]
Any reason not to do this: kahowell/lightblue-client@c127c9eb0655069d392811330d5d7784ae639880?

**Comment by alechenninger** [comment]
Because that's backwards incompatible, users would have to close the client.

**Comment by alechenninger** [comment]
For instance, better than that would be to accept the HTTP client as a dependency (which is much of what I've babbled about in this issue for other reasons), which has the same issue. Which is why I was saying by default you could instead use an implementation which did not require closing (as in, one that is implemented which vanilla, no-threading, java.net, which would probably be ideal in a servlet environment anyway I suspect).

**Comment by kahowell** [comment]
I don't think of this as an incompatibility, as you'd need to pull in the newer version for this to even affect you. And even as an incompatibility, I feel it is worth doing. Handling the closing/opening of the client automatically is a bit too much hand-holding IMHO.

**Comment by alechenninger** [comment]
> Handling the closing/opening of the client automatically is a bit too much hand-holding IMHO.

I agree with that completely. There are still other reasons to inject a client though (testability, inversion of control).
