### ISSUE TITLE
LightblueHttpClient is using HttpClientNoAuth, which has been depreciated 

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-client#50]
Appears that ApacheHttpClients has been preferred over HttpClientNoAuth

**Comment by alechenninger** [comment]
This is fixed as of #42, but there is the deprecated `LightblueProxyServlet` which is still using this. At this point it's been deprecated for a little while now so probably save to remove.

**Comment by dcrissman** [comment]
I see LightblueHttpClient no longer uses the depreciated class.

Is there any reason to keep these classes around?
http/src/main/java/com/redhat/lightblue/client/http/LightblueProxyServlet.java
http/src/main/java/com/redhat/lightblue/client/http/auth/HttpClientNoAuth.java

**Comment by dcrissman** [comment]
@alechenninger I think our messages crossed paths. Thanks for the update.

I will create a new issue for their removal.
