### ISSUE TITLE
Cleanup new ObjectMapper

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-client#65]
A static DEFAULT_MAPPER was on LightblueHttpClient until https://github.com/lightblue-platform/lightblue-client/pull/64 which moved it to LightblueResponse.  There is also one on a JSON class.  Given DEFAULT_MAPPER sets up some things like date format and it can be reused it would be good to use one instance by default.

**Comment by dcrissman** [comment]
Fixed in #64

**Comment by jewzaam** [comment]
@dcrissman one instance is fixed in that PR, not all:
* https://github.com/lightblue-platform/lightblue-client/blob/1c673a4047dde8d080482301d7d0c9700cc0619f/core/src/main/java/com/redhat/lightblue/client/util/JSON.java#L19
* https://github.com/lightblue-platform/lightblue-client/blob/b64d42c440c771ae2c4217cb68a546cf088ee201/core/src/main/java/com/redhat/lightblue/client/json/LightBlueJsonHelperImpl.java#L15

And maybe this one, but it's a unit test:
* https://github.com/lightblue-platform/lightblue-client/blob/cd2d528dcf9295eac350c0286563569c3ffe09f6/core/src/test/java/com/redhat/lightblue/client/response/TestLightblueResponse.java#L41

**Comment by dcrissman** [comment]
It would make sense to me to move the DEFAULT_MAPPER to JSON.java so that it can be reused.

@jewzaam Are you thinking you'd want the ability to set/change the DEFAULT_MAPPER that the client uses?

**Comment by jewzaam** [comment]
So that for a particular use of the client it could be globally overridden instead of passed around?  May be utility in that, but each has its problems.

**Comment by dcrissman** [comment]
I am thinking both. Set it once and forget (or don't and use DEFAULT_MAPPER) if you want, but LightblueResponse and LightblueHttpClient will continue to have constructors that take an instance of ObjectMapper in case there is need for a one-off that way.
