### ISSUE TITLE
rename http (and others) projects like standard

### ISSUE THREAD

**Issue by luan-cestari** [lightblue-platform/lightblue-client#67]
Http is like:
        <dependency>
            <groupId>com.redhat.lightblue.client</groupId>
            <artifactId>http</artifactId>
            <version>1.2.0-SNAPSHOT</version>
        </dependency>

And it should be like:
        <dependency>
            <groupId>com.redhat.lightblue.rest</groupId>
            <artifactId>lightblue-rest-metadata</artifactId>
            <version>1.3.0-SNAPSHOT</version>
            <classifier>classes</classifier>
        </dependency>

**Comment by jewzaam** [comment]
Are you taking about maven groupId, artifactId, and version?

**Comment by luan-cestari** [comment]
yes the GAV. In the http module would be just the A.

**Comment by jewzaam** [comment]
It's already set to 'lightblue-client-http'

https://github.com/lightblue-platform/lightblue-client/blob/master/http/pom.xml#L9

**Comment by luan-cestari** [comment]
Sorry for this issue, I openned looking and old reference (made an PR related to this https://github.com/paterczm/lightblue-test-utils/pull/3 )

**Comment by luan-cestari** [comment]
closing this issue
