### ISSUE TITLE
Expressions should use quotes

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-client#80]
Expressions do not require quotation marks around string fields.

I know this is true for ValueQuery expressions, but we should check other expressions as well to ensure consistency.

**Comment by jewzaam** [comment]
Should quotes be optional or required?

**Comment by dcrissman** [comment]
I am fine with optional, just seems that they should be supported. That does beg the question though if we are going to start supporting/forcing escape characters?

**Comment by jewzaam** [comment]
Could create an issue for it and leave it for now, since it's an identified gap..

**Comment by bserdar** [comment]
Expression backend is now json, so this is no longer a problem.
