### ISSUE TITLE
Query method consistency

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-client#89]
The Query hierarchy sometimes has static factory methods for constructors, but not always. I think we should be consistent. Either all constructors also have a factory method, or none of them do.

In general, I find myself asking if I can directly call the constructor, then why do I need a static factory method? But I don't really care, so long as we are consistent.

**Comment by jblashka** [comment]
The static factory methods aren't strictly necessary; they were created for convenience/readability purposes.

lightblueRequest.where(new NaryLogicalQuery(new ValueQuery("name = blah"), new ValueQuery("label = blah")))

vs

lightblueRequest.where(and(withValue("name = blah"), withValue("label = blah")));

**Comment by jewzaam** [comment]
+1 for consistency

I'm for the static methods as it does aid in readability.  The class maps to the language spec, but those static methods are more developer friendly.

**Comment by bserdar** [comment]
These classes are now deprecated, and the new expression classes have static methods.
