### ISSUE TITLE
LightblueHttpClient does not reuse HTTPS connections?

### ISSUE THREAD

**Issue by kahowell** [lightblue-platform/lightblue-client#98]
From a cursory glance at `LightblueHttpClient`, it looks like each call to `callService` creates a new instance of `CloseableHttpClient`. I imagine this forces a new SSL/TLS handshake on each call (somewhat significant overhead when using HTTPS). Would it be possible to reuse instances of `CloseableHttpClient` here?

**Comment by jblashka** [comment]
I believe this is a duplicate of issue #42

**Comment by kahowell** [comment]
Pretty much. #42 has more details on a possible implementation.
